### ISSUE TITLE
SteamTools

### ISSUE THREAD

**Issue by yessiub** [RumbleFrog/Steam-Group-Invite#2]
When trying to run the plugin it is giving the following error:

Steam-Group-Invite.smx (Steam Group Invite): Required extension "SteamTools" file("steamtools.ext") not running

There is no mention of SteamTools only SteamWorks on the github page for this plugin.

Can you please advise?

I am running SteamWorks and SteamCore from previous installations and plugins.

**Comment by rumblefrog** [comment]
Thank you, I originally included SteamTools because some people are known to have a compound of it. New release made it optional.
